In [1]:
import numpy as np

In [3]:
data = np.array([2,3,4,55,5])

In [9]:
npt = np.array([[6,8,9],[4,8,7]])
print(npt.shape)
print(npt[0, 0], npt[0, 1], npt[1, 0])

(2, 3)
6 8 4


In [10]:
data = np.random.random((2,2))

In [11]:
print(data)

[[0.44720873 0.7179942 ]
 [0.62272772 0.91572956]]


In [17]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)
a = np.empty_like(x)
print(a)
print(y)
t = np.empty_like(x)
print(t)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1,2])
print(x+v)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [51]:
import numpy as np
 
a = np.array(
       [[0, 1],
       [2, 3],
       [4, 5]])
b = np.array([10,20])
c = np.array([0, 1, 2])
d=np.array([[10],[20],[30]])
e = np.array([[10],[20],[30]])


In [52]:
print("a = \n",a , " \n a.shape =",a.shape)
print("b = \n",b , " \n b.shape =",b.shape)
print("c = \n",c , " \n c.shape =",c.shape)
print("d = \n",d , " \n d.shape =",d.shape)
print("e = \n",e , " \n e.shape =",e.shape)

a = 
 [[0 1]
 [2 3]
 [4 5]]  
 a.shape = (3, 2)
b = 
 [10 20]  
 b.shape = (2,)
c = 
 [0 1 2]  
 c.shape = (3,)
d = 
 [[10]
 [20]
 [30]]  
 d.shape = (3, 1)
e = 
 [[10]
 [20]
 [30]]  
 e.shape = (3, 1)


In [71]:
f = np.array([[1,2,3],[2,2,3]])

In [72]:
print(f*c)

[[0 2 6]
 [0 2 6]]


In [55]:

 
"""
1. element-wise 运算，维度对应关系
b的第0维和a的第1维对齐（维度倒着对齐）
b重复和a的每行运算，输入结果为3*2维
"""
b*a
array([[  0,  20],
       [ 20,  60],
       [ 40, 100]])
 
"""
1.1 相应维度不对齐，并且长度都不为1，非法
"""
c*a
ValueError: operands could not be broadcast together with shapes (3,) (3,2) 
 
#c = np.array([0, 1, 2])
d=np.array([[10],[20],[30]])
 
"""
1.2 相应维度可广播
c在行方向复制扩充，d在列方向
"""
d+c
array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])
 
"""
2.1 非element-wise运算，按运算定义来计算，基础对应维度上不适用广播
    如果基础对应维度不对齐，会直接报错
"""
np.dot(d,c)  
ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)
#np.dot(c,d)是合法的
 
"""
2.2 非element-wise运算
    基础维度合法对齐时，在更高维度上是element-wise对应的（以基础对应块为单位），会适用广播规则
"""
a=np.random.randint(24,size=[2,3,4])
b=np.random.randint(12,size=[4,2])
np.dot(a,b).shape    #能合法进行运算
Out[111]: (2, 3, 2)

SyntaxError: invalid syntax (1562358800.py, line 15)

In [58]:
print(np.array([1,2]).shape)

(2,)


In [77]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 4))
print(vv)
vv = np.tile(v, 2)
print(vv)
vv = np.tile(v, (1,2))
print(vv)



[[1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 0 1 1 0 1]]
[1 0 1 1 0 1]
[[1 0 1 1 0 1]]


In [80]:
a ={"name ":'wangxinchao',"age":19}
b = a
a["age"] = 20
print(b)
# {'name ': 'wangxinchao', 'age': 20}

x = [12,3,4,4]
y = x
x[0] = 13
print(x)
print(y)
# [13, 3, 4, 4]

# 失效了
x = 23
y = x
print(y)
x = 23+3
print(y)
# 23

{'name ': 'wangxinchao', 'age': 20}


In [96]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数
np.random.rand(3, 3) # 注意这里传入的不是元组，每个维度大小分开输入

# randn生成了N(0,I)的标准正态分布：
np.random.randn(3)
np.random.randn(2, 2)


# randint可以指定生成随机整数的最小值最大值（不包含）和维度大小
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)


# choice可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1]) # replace=False表示不允许出现重复元素
np.random.choice(my_list, (3,3)) # 当不指定参数时，默认均匀采样，可以出现重复元素

# 当返回的元素个数与原列表相同时，不放回抽样等价于使用permutation函数，即打散原列表
np.random.permutation(my_list)


array(['c', 'b', 'd', 'a'], dtype='<U1')

array([ 8.27698122,  8.43816069, 13.13586632])

In [90]:
x = [12,3,4,4]
y = x
x[0] = 13
print(x)
print(y)
# [13, 3, 4, 4]

[13, 3, 4, 4]
[13, 3, 4, 4]


In [100]:
import numpy as np
import matplotlib.pyplot as plt

# 生成一个二维数据
x = np.array(range(12))
x = np.reshape(x, (3,4))
print(x)
# 输出为：
# [[ 0  1  2  3]
#  [ 4  5  6  7]
x = np.reshape(x, (4,3))
print(x)

x = np.reshape(x, (2,2,3))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [106]:
# 生成一个二维数据
x = np.array(range(12))
x = np.reshape(x, (3,4))
print(x)
# 输出为：
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 在多维数组的最后一维再增加一个维度
y1 = np.expand_dims(x, axis=x.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]
 [3]]
